# Generated by Django 5.2.4 on 2025-08-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default='Best comment'),
        ),
    ]
